/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentServicesRouteImport } from './routes/student-services'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as PrincipalRouteImport } from './routes/principal'
import { Route as PlacementsRouteImport } from './routes/placements'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommitteesRouteImport } from './routes/committees'
import { Route as AntiRaggingRouteImport } from './routes/anti-ragging'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const StudentServicesRoute = StudentServicesRouteImport.update({
  id: '/student-services',
  path: '/student-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipalRoute = PrincipalRouteImport.update({
  id: '/principal',
  path: '/principal',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementsRoute = PlacementsRouteImport.update({
  id: '/placements',
  path: '/placements',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteesRoute = CommitteesRouteImport.update({
  id: '/committees',
  path: '/committees',
  getParentRoute: () => rootRouteImport,
} as any)
const AntiRaggingRoute = AntiRaggingRouteImport.update({
  id: '/anti-ragging',
  path: '/anti-ragging',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/anti-ragging': typeof AntiRaggingRoute
  '/committees': typeof CommitteesRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/downloads': typeof DownloadsRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/library': typeof LibraryRoute
  '/notices': typeof NoticesRoute
  '/placements': typeof PlacementsRoute
  '/principal': typeof PrincipalRoute
  '/scholarships': typeof ScholarshipsRoute
  '/student-services': typeof StudentServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/anti-ragging': typeof AntiRaggingRoute
  '/committees': typeof CommitteesRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/downloads': typeof DownloadsRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/library': typeof LibraryRoute
  '/notices': typeof NoticesRoute
  '/placements': typeof PlacementsRoute
  '/principal': typeof PrincipalRoute
  '/scholarships': typeof ScholarshipsRoute
  '/student-services': typeof StudentServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/anti-ragging': typeof AntiRaggingRoute
  '/committees': typeof CommitteesRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/downloads': typeof DownloadsRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/library': typeof LibraryRoute
  '/notices': typeof NoticesRoute
  '/placements': typeof PlacementsRoute
  '/principal': typeof PrincipalRoute
  '/scholarships': typeof ScholarshipsRoute
  '/student-services': typeof StudentServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/anti-ragging'
    | '/committees'
    | '/contact'
    | '/departments'
    | '/downloads'
    | '/events'
    | '/gallery'
    | '/library'
    | '/notices'
    | '/placements'
    | '/principal'
    | '/scholarships'
    | '/student-services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/anti-ragging'
    | '/committees'
    | '/contact'
    | '/departments'
    | '/downloads'
    | '/events'
    | '/gallery'
    | '/library'
    | '/notices'
    | '/placements'
    | '/principal'
    | '/scholarships'
    | '/student-services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/anti-ragging'
    | '/committees'
    | '/contact'
    | '/departments'
    | '/downloads'
    | '/events'
    | '/gallery'
    | '/library'
    | '/notices'
    | '/placements'
    | '/principal'
    | '/scholarships'
    | '/student-services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AntiRaggingRoute: typeof AntiRaggingRoute
  CommitteesRoute: typeof CommitteesRoute
  ContactRoute: typeof ContactRoute
  DepartmentsRoute: typeof DepartmentsRoute
  DownloadsRoute: typeof DownloadsRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  LibraryRoute: typeof LibraryRoute
  NoticesRoute: typeof NoticesRoute
  PlacementsRoute: typeof PlacementsRoute
  PrincipalRoute: typeof PrincipalRoute
  ScholarshipsRoute: typeof ScholarshipsRoute
  StudentServicesRoute: typeof StudentServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student-services': {
      id: '/student-services'
      path: '/student-services'
      fullPath: '/student-services'
      preLoaderRoute: typeof StudentServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principal': {
      id: '/principal'
      path: '/principal'
      fullPath: '/principal'
      preLoaderRoute: typeof PrincipalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placements': {
      id: '/placements'
      path: '/placements'
      fullPath: '/placements'
      preLoaderRoute: typeof PlacementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committees': {
      id: '/committees'
      path: '/committees'
      fullPath: '/committees'
      preLoaderRoute: typeof CommitteesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anti-ragging': {
      id: '/anti-ragging'
      path: '/anti-ragging'
      fullPath: '/anti-ragging'
      preLoaderRoute: typeof AntiRaggingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AntiRaggingRoute: AntiRaggingRoute,
  CommitteesRoute: CommitteesRoute,
  ContactRoute: ContactRoute,
  DepartmentsRoute: DepartmentsRoute,
  DownloadsRoute: DownloadsRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  LibraryRoute: LibraryRoute,
  NoticesRoute: NoticesRoute,
  PlacementsRoute: PlacementsRoute,
  PrincipalRoute: PrincipalRoute,
  ScholarshipsRoute: ScholarshipsRoute,
  StudentServicesRoute: StudentServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
